repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy --config-file=mypy.ini .
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        entry: uv run pytest tests/
        language: system
        pass_filenames: false
        always_run: true