class Constants:
    ANTHROPIC_CHAT_TEXT = "claude-3-5-sonnet-20241022"  # LLM model used for text completion
    AWS3_LINK_EXPIRATION_SECONDS = 1200  # duration of an AWS S3 link
    DISCUSSION_CACHED_DURATION = 90  # minutes before a discussion is cleared
    GOOGLE_CHAT_ALL = "models/gemini-2.0-flash"  # LLM model used for speech to text and text completion
    INFORMANT_AWS_BUCKET = "hyperscribe"
    INFORMANT_END_OF_MESSAGES = "EOF"
    LABEL_ENCOUNTER_COPILOT = "Encounter Copilot"
    MAX_ATTEMPTS_LLM_HTTP = 3
    MAX_ATTEMPTS_LLM_JSON = 3
    MAX_ATTEMPTS_CANVAS_SERVICES = 3
    MAX_WORKERS = 10  # max parallel executions
    MEMORY_LOG_LABEL = "main"
    OPENAI_CHAT_AUDIO = "gpt-4o-audio-preview"  # LLM model used for speech to text
    OPENAI_CHAT_TEXT = "gpt-4o"  # LLM model used for text completion
    VENDOR_ANTHROPIC = "Anthropic"
    VENDOR_GOOGLE = "Google"
    VENDOR_OPENAI = "OpenAI"
    #
    FAUX_NOTE_UUID = "_NoteUuid"
    FAUX_PATIENT_UUID = "_PatientUuid"
    FAUX_PROVIDER_UUID = "_ProviderUuid"
    # schema_key field values of the Command view (canvas_sdk.v1.data.command.Command)
    SCHEMA_KEY_ADJUST_PRESCRIPTION = "adjustPrescription"
    SCHEMA_KEY_ALLERGY = "allergy"
    SCHEMA_KEY_ASSESS = "assess"
    SCHEMA_KEY_CLOSE_GOAL = "closeGoal"
    SCHEMA_KEY_DIAGNOSE = "diagnose"
    SCHEMA_KEY_FAMILY_HISTORY = "familyHistory"
    SCHEMA_KEY_FOLLOW_UP = "followUp"
    SCHEMA_KEY_GOAL = "goal"
    SCHEMA_KEY_HISTORY_OF_PRESENT_ILLNESS = "hpi"
    SCHEMA_KEY_IMAGING_ORDER = "imagingOrder"
    SCHEMA_KEY_IMMUNIZE = "immunize"
    SCHEMA_KEY_INSTRUCT = "instruct"
    SCHEMA_KEY_LAB_ORDER = "labOrder"
    SCHEMA_KEY_MEDICAL_HISTORY = "medicalHistory"
    SCHEMA_KEY_MEDICATION = "medicationStatement"
    SCHEMA_KEY_PERFORM = "perform"
    SCHEMA_KEY_PHYSICAL_EXAM = "exam"
    SCHEMA_KEY_PLAN = "plan"
    SCHEMA_KEY_PRESCRIPTION = "prescribe"
    SCHEMA_KEY_QUESTIONNAIRE = "questionnaire"
    SCHEMA_KEY_REASON_FOR_VISIT = "reasonForVisit"
    SCHEMA_KEY_REFER = "refer"
    SCHEMA_KEY_REFILL = "refill"
    SCHEMA_KEY_REMOVE_ALLERGY = "removeAllergy"
    SCHEMA_KEY_RESOLVE_CONDITION = "resolveCondition"
    SCHEMA_KEY_REVIEW_OF_SYSTEM = "ros"
    SCHEMA_KEY_STOP_MEDICATION = "stopMedication"
    SCHEMA_KEY_STRUCTURED_ASSESSMENT = "structuredAssessment"
    SCHEMA_KEY_SURGERY_HISTORY = "surgicalHistory"
    SCHEMA_KEY_TASK = "task"
    SCHEMA_KEY_UPDATE_DIAGNOSE = "updateDiagnosis"
    SCHEMA_KEY_UPDATE_GOAL = "updateGoal"
    SCHEMA_KEY_VITALS = "vitals"
    #
    CUSTOMER_IDENTIFIER = "CUSTOMER_IDENTIFIER"
    #
    SECRET_TEXT_VENDOR = "VendorTextLLM"
    SECRET_TEXT_KEY = "KeyTextLLM"
    SECRET_AUDIO_VENDOR = "VendorAudioLLM"
    SECRET_AUDIO_KEY = "KeyAudioLLM"
    SECRET_SCIENCE_HOST = "ScienceHost"
    SECRET_ONTOLOGIES_HOST = "OntologiesHost"
    SECRET_PRE_SHARED_KEY = "PreSharedKey"
    SECRET_AUDIO_HOST = "AudioHost"
    SECRET_AUDIO_INTERVAL = "AudioIntervalSeconds"
    SECRET_AWS_KEY = "AwsKey"
    SECRET_AWS_SECRET = "AwsSecret"
    SECRET_AWS_REGION = "AwsRegion"
    SECRET_AWS_BUCKET = "AwsBucket"
    SECRET_STRUCTURED_RFV = "StructuredReasonForVisit"
    SECRET_AUDIT_LLM = "AuditLLMDecisions"
