"""Dispense-field derivation for prescription recommendations.

When the scribe recommends a new prescription, the provider should not have to
hand-fill the dispense fields the Rx form requires (``type_to_dispense``,
``quantity_to_dispense``, ``refills``). This module fills them while keeping the
hallucination/medical-error surface as small as possible:

1. ``type_to_dispense`` is chosen *deterministically* from the FDB medication's
   first dispensing form — it is never generated by a model. The value is
   emitted in the encoded ``ndc|qty|code`` form the order-row dropdown uses to
   pre-select an option.
2. ``quantity_to_dispense`` is, when the provider stated it, passed through
   verbatim. Otherwise an LLM is asked ONLY to interpret the directions into a
   dosing frequency (units per dose x doses per day); the quantity is then
   recomputed *arithmetically* here. The model never gets to be the sole source
   of the number — and if it reports it cannot read a clear frequency
   (``derivable=false``), or its own estimate disagrees with the arithmetic, we
   leave the field blank for the provider to fill.
3. ``refills`` defaults to ``0`` (a single fill) unless the provider explicitly
   stated a count. We never silently grant refills the provider did not ask for.

Every value remains an editable default in the UI and the prescribe path still
requires provider sign-off (originate + review) before anything is transmitted.
"""

from __future__ import annotations

import json
import re
from decimal import Decimal
from http import HTTPStatus
from typing import Any

from logger import log

from canvas_sdk.clients.llms.libraries import LlmAnthropic

from hyperscribe.scribe.recommendations import _drug_class
from hyperscribe.scribe.recommendations._medication_match import sanitize_sig
from hyperscribe.scribe.recommendations.schemas import DosageDerivation
from hyperscribe.structures.medication_detail import MedicationDetail
from hyperscribe.structures.medication_detail_quantity import MedicationDetailQuantity

# The model's own quantity estimate must agree with the arithmetic we compute
# from its reported frequency to within this fraction; a larger gap means the
# model is internally inconsistent, so we distrust it and leave the field blank.
_CROSS_CHECK_TOLERANCE = 0.2

# Sanity ceiling. A derived quantity above this almost certainly reflects a
# misread frequency (e.g. mistaking "once weekly" for daily); drop it rather
# than pre-fill an implausible dispense amount.
_MAX_QUANTITY = 5000.0

# When a chronic maintenance med is prescribed without a stated duration, assume
# a 30-day month to compute the quantity (Brigade Q3: unstated-duration Rx imply
# 30 days in the majority). Used only for the quantity math — never written to
# the days_supply field, which Brigade leaves blank ~56% of the time.
_ASSUMED_DAYS_SUPPLY = 30

# Dispense-form classification (Brigade instance data, Q1): the dispense unit is
# largely determined by the form, and the right quantity depends on which family
# it is. ``container`` forms (a tube/bottle/inhaler/pack…) dispense as ONE
# package — computing dose x freq x days for an inhaler is the bug we're fixing.
# ``injectable`` packaging (pens/syringes/vials, often boxes of N) is genuinely
# ambiguous, so we leave it for the provider. Countable and bare volume/mass
# forms get the arithmetic. Matched against ``clinical_quantity_description`` with
# word boundaries so "suspension" never matches "pen", etc.
_INJECTABLE_RE = re.compile(r"\b(syringe|pen|vial|pre-?filled|cartridge|ampul\w*)\b", re.IGNORECASE)
_CONTAINER_RE = re.compile(
    r"\b(tube|bottle|dropper|jar|canister|inhaler|aerosol|box|kit|blister|"
    r"dispensing pack|packet|pack|device|wipe|pad|film|applicator)\b",
    re.IGNORECASE,
)
_COUNTABLE_QUALIFIERS = {"tablet", "capsule", "patch", "lozenge", "suppository", "troche", "strip"}
_VOLUME_MASS_QUALIFIERS = {"milliliter", "gram"}

# Multi-step / titration / dose-range sigs ("2 tabs day 1 then 1 daily",
# "1-2 tablets") can't be reduced to a single dose x freq, so a naive
# computation would be wrong. Refuse and let the provider fill the quantity.
_MULTISTEP_RE = re.compile(
    r"\bthen\b|\btaper\b|\bfollowed by\b|\bthereafter\b|\bday\s*1\b|\bon days?\b|"
    r"\bdays?\s*\d+\s*[-–]\s*\d+\b",
    re.IGNORECASE,
)
_DOSE_RANGE_RE = re.compile(
    r"\b\d+(?:\.\d+)?\s*(?:-|–|to)\s*\d+(?:\.\d+)?\s*"
    r"(?:tablet|tab|capsule|cap|puff|drop|spray|unit|lozenge|patch|mcg|mg|mL|ml|g)s?\b",
    re.IGNORECASE,
)

# Leading number in a stated quantity, so "6 tablets" -> "6", "30 capsules" -> "30".
_LEADING_NUMBER_RE = re.compile(r"^(\d+(?:\.\d+)?)")

# Fractional / split-tablet dosing ("half a tablet", "1/2 tab", "0.5 tablet").
# When the per-dose amount is fractional we must NOT fall back to 1 unit/dose —
# that would over-dispense ~2x — so the countable default is suppressed for these
# and the quantity is left for the provider unless the model read the amount.
_FRACTIONAL_DOSE_RE = re.compile(r"\bhalf\b|\bquarter\b|½|¼|¾|\b\d*\.\d+\b|\b\d+\s*/\s*\d+\b", re.IGNORECASE)


def _dispense_form_class(quantity_form: MedicationDetailQuantity) -> str:
    """Classify the dispensing form: container | injectable | countable | volume_mass.

    Container/injectable are detected from the form description (a named package);
    countable vs. volume/mass falls back to the NCPDP unit qualifier. An unknown
    qualifier defaults to ``countable`` so the compute path runs (and then refuses
    if the sig isn't parseable) rather than silently emitting 1.
    """
    description = (quantity_form.clinical_quantity_description or "").lower()
    qualifier = (quantity_form.ncpdp_quantity_qualifier_description or "").strip().lower()
    if _INJECTABLE_RE.search(description):
        return "injectable"
    # Liquids (mL) are divisible: compute the volume from the sig rather than
    # dispensing one container — even when the form names a bottle ("100 mL
    # bottle"). A blanket 1-container default under-supplies multi-day courses
    # (10 mL BID x 10d needs 200 mL, not one 100 mL bottle). Checked before the
    # container match for that reason.
    if qualifier in _VOLUME_MASS_QUALIFIERS and qualifier == "milliliter":
        return "volume_mass"
    if _CONTAINER_RE.search(description):
        return "container"
    if qualifier in _COUNTABLE_QUALIFIERS:
        return "countable"
    if qualifier in _VOLUME_MASS_QUALIFIERS:
        return "volume_mass"
    return "countable"


def _is_multistep_sig(sig: str) -> bool:
    """True if the sig is a multi-step/titration/dose-range that we won't compute."""
    return bool(_MULTISTEP_RE.search(sig) or _DOSE_RANGE_RE.search(sig))


def _is_fractional_dose_sig(sig: str) -> bool:
    """True if the sig implies a fractional per-dose amount (half/quarter/decimal).

    Used to suppress the countable 1-unit/dose default, since defaulting a
    fractional dose to 1 unit would over-dispense.
    """
    return bool(_FRACTIONAL_DOSE_RE.search(sig))


_DOSAGE_SYSTEM_PROMPT = (
    "You are a clinical pharmacy assistant. You are given a medication's dispensing form and the "
    "prescriber's directions (the sig). Your ONLY task is to interpret the directions into a dosing "
    "frequency: how many dosage-form units are taken per administration (units_per_dose) and how "
    "many administrations there are per day (doses_per_day). "
    "For countable forms (tablets, capsules, patches), if the directions state a clear frequency but "
    "not the number of units per dose (e.g. 'twice daily' without 'one tablet'), assume 1 unit per "
    "administration and set derivable=true. "
    "Do NOT invent a frequency the directions do not state. If there is no clear frequency at all "
    "(e.g. 'as directed', or 'as needed' with no schedule), set derivable=false and leave the numeric "
    "fields null. Never guess. "
    "Set discrete=true for countable forms (tablets, capsules, patches) and false for measured "
    "forms (mL, grams, ounces)."
)


def derive_dispense_fields(
    detail: MedicationDetail | None,
    *,
    stated_sig: str | None,
    stated_days_supply: int | None,
    stated_quantity: str | None,
    stated_refills: int | None,
    client: LlmAnthropic,
) -> dict[str, Any]:
    """Return the dispense-related proposal fields to merge into the Rx proposal.

    Keys returned: ``type_to_dispense`` and ``type_to_dispense_label`` (only when
    the medication resolved to an FDB form), ``refills`` (always), and
    ``quantity_to_dispense`` (only when stated or confidently derived).
    """
    out: dict[str, Any] = {}

    # 1. Dispense form — deterministic, straight from FDB. Never generated.
    quantity_form: MedicationDetailQuantity | None = None
    if detail and detail.quantities:
        quantity_form = detail.quantities[0]
        # Mirror order-row.js encodeClinicalQuantity(ndc, erxQuantity, code) so the
        # dropdown pre-selects this option on load.
        out["type_to_dispense"] = (
            f"{quantity_form.representative_ndc}|{quantity_form.quantity}|{quantity_form.ncpdp_quantity_qualifier_code}"
        )
        out["type_to_dispense_label"] = (
            quantity_form.clinical_quantity_description or quantity_form.ncpdp_quantity_qualifier_description
        )

    # 2. Therapeutic class gates the chronic-only behaviors (refill suggestion and
    #    the 30-day quantity assumption). Anything not confidently chronic — acute,
    #    neither, unknown — falls back to the safe default.
    drug_class = _drug_class.classify(detail.description if detail else None)
    controlled = _drug_class.is_controlled(detail.description if detail else None)

    # 3. Refills — stated wins; chronic non-controlled meds get the class default
    #    (Q4), but ONLY when no duration was dictated. A stated days-supply implies
    #    a defined fill (often a trial: "amlodipine for 30 days, reassess"), so we
    #    don't auto-inflate refills on top of it. Everything else: a single fill.
    stated_days = _coerce_positive_int(stated_days_supply)
    if stated_refills is not None:
        out["refills"] = stated_refills
    elif drug_class.bucket == _drug_class.CHRONIC and not controlled and stated_days is None:
        out["refills"] = drug_class.refills
    else:
        out["refills"] = 0

    # 4. Quantity — provider-stated wins; otherwise branch on the dispense form.
    stated = _coerce_quantity(stated_quantity)
    if stated is not None:
        out["quantity_to_dispense"] = stated
        return out

    form_class = _dispense_form_class(quantity_form) if quantity_form is not None else None

    # Packaged goods dispense as one container — never compute dose x freq x days
    # for a tube/bottle/inhaler/pack.
    if form_class == "container":
        out["quantity_to_dispense"] = "1"
        return out

    # Injectable packaging (pens/syringes/vials, often boxes of N) — the box count
    # isn't knowable from the sig, so leave it for the provider.
    if form_class == "injectable":
        return out

    sig = sanitize_sig(stated_sig)
    # Multi-step / titration / dose-range sigs can't be reduced to a single
    # dose x frequency; refuse rather than mis-compute.
    if _is_multistep_sig(sig):
        return out

    days = stated_days
    # No dictated duration but a chronic maintenance med: assume a 30-day month to
    # compute the quantity. Not written to the days_supply field.
    if days is None and drug_class.bucket == _drug_class.CHRONIC:
        days = _ASSUMED_DAYS_SUPPLY

    # Need a dispensing form, a days supply, AND directions to compute without
    # guessing. (``quantity_form`` is non-None only when ``detail`` resolved, but
    # spell ``detail`` out for the type checker.)
    if detail is None or quantity_form is None or days is None or not sig:
        return out

    derived = _derive_quantity(detail, quantity_form, sig, days, client, form_class)
    if derived is not None:
        out["quantity_to_dispense"] = derived
    return out


def _derive_quantity(
    detail: MedicationDetail,
    quantity_form: MedicationDetailQuantity,
    sig: str,
    days_supply: int,
    client: LlmAnthropic,
    form_class: str | None,
) -> str | None:
    """Ask the model to read the frequency, then compute the quantity ourselves."""
    client.reset_prompts()
    client.set_system_prompt([_DOSAGE_SYSTEM_PROMPT])
    client.set_user_prompt([_dosage_user_prompt(detail, quantity_form, sig, days_supply)])
    client.set_schema(DosageDerivation)

    try:
        response = client.request()
    except Exception:
        log.exception("LLM request failed for dosage derivation")
        return None

    if response.code != HTTPStatus.OK:
        log.info(f"LLM returned {response.code} for dosage derivation")
        return None

    try:
        parsed = DosageDerivation.model_validate(json.loads(response.response))
    except Exception:
        # Do not log response.response: it is derived from the note and may contain PHI.
        log.exception("Failed to parse dosage derivation response")
        return None

    doses = parsed.doses_per_day
    units = parsed.units_per_dose
    # Countable forms: a clear frequency with an unstated per-dose count means
    # 1 unit/dose by convention ("twice daily" = 1 tablet twice daily). Suppressed
    # for fractional/split-dose sigs, where defaulting to 1 would over-dispense.
    countable_default_applies = units is None and form_class == "countable" and doses is not None and doses > 0
    if countable_default_applies and not _is_fractional_dose_sig(sig):
        units = 1.0

    # Refuse rather than guess.
    if not parsed.derivable or units is None or doses is None:
        return None
    if units <= 0 or doses <= 0:
        return None

    # Arithmetic is authoritative — the model only interpreted the directions.
    computed = units * doses * days_supply
    if not (0 < computed <= _MAX_QUANTITY):
        log.info(f"Derived dosage quantity {computed} out of plausible range; leaving blank")
        return None

    # Internal-consistency check: the model's own estimate must agree with our
    # arithmetic. A large gap means it was confused — distrust and leave blank.
    if parsed.quantity_to_dispense is not None and parsed.quantity_to_dispense > 0:
        if abs(parsed.quantity_to_dispense - computed) / computed > _CROSS_CHECK_TOLERANCE:
            log.info(
                f"Dosage cross-check failed (computed={computed}, model={parsed.quantity_to_dispense}); "
                "leaving quantity blank"
            )
            return None

    if parsed.discrete:
        return str(int(round(computed)))
    return _format_decimal(computed)


def _dosage_user_prompt(
    detail: MedicationDetail,
    quantity_form: MedicationDetailQuantity,
    sig: str,
    days_supply: int,
) -> str:
    return "\n".join(
        [
            f"Medication: {detail.description}",
            f"Dispensing form: {quantity_form.quantity}, {quantity_form.ncpdp_quantity_qualifier_description}.",
            f"Prescriber directions (sig): {sig}",
            f"Days supply to cover: {days_supply}",
            "",
            "Interpret the directions into units_per_dose and doses_per_day, then report "
            "quantity_to_dispense = units_per_dose * doses_per_day * days supply. "
            "If the directions are not specific enough to do this, set derivable=false.",
        ]
    )


def _coerce_quantity(value: str | None) -> str | None:
    """Normalize a stated quantity to a clean, positive, trailing-zero-free string.

    Extracts the leading number so unit-suffixed values from the note ("6 tablets",
    "30 capsules") normalize to the bare count ("6", "30") rather than failing —
    otherwise the raw string would slip through and break Surescripts validation.
    Returns None when there is no leading positive number, so the caller falls back
    to derivation.
    """
    if value is None:
        return None
    match = _LEADING_NUMBER_RE.match(str(value).strip())
    if not match:
        return None
    try:
        decimal_value = Decimal(match.group(1))
    except (ArithmeticError, ValueError):
        return None
    if not decimal_value.is_finite() or decimal_value <= 0:
        return None
    return _format_decimal(decimal_value)


def _coerce_positive_int(value: int | None) -> int | None:
    if value is None:
        return None
    try:
        days = int(value)
    except (TypeError, ValueError):
        return None
    return days if days > 0 else None


def _format_decimal(value: float | Decimal) -> str:
    """Render a quantity with at most 2 decimals and no trailing zeros.

    The Surescripts NewRx wire format (enforced by ``_rx_validation``) rejects
    trailing-zero decimals like ``"1.0"`` or ``"1."``; ``Decimal.normalize`` plus
    fixed-point formatting yields ``"1"``, ``"2.5"``, ``"150"``.
    """
    decimal_value = Decimal(str(value)).quantize(Decimal("0.01")).normalize()
    return format(decimal_value, "f")
